### ISSUE TITLE
Arm64 for macOS and Linux

### ISSUE THREAD

**Issue by iMonZ** [overleaf/overleaf#957] opened 2021-09-14 14:21 UTC
Since more and more systems are switching to arm64 like macOS and Linux it would be great to provide an arm64 docker image.

**Comment by mathiasgredal** [comment] 2021-09-21 22:07
I have gotten overleaf to work on arm64 inside a virtual machine on my m1, and on and oracle ampere a1 compute instance using a couple of hacks which I have collected in this commit: https://github.com/mathiasgredal/overleaf/commit/44f1a83ab963a6ee8a82bcc493243b57602e1460

**Comment by lpyparmentier** [comment] 2022-01-03 13:00
> I have gotten overleaf to work on arm64 inside a virtual machine on my m1 macbook, and on an oracle ampere a1 compute instance using a couple of hacks which I have collected in this commit: [mathiasgredal@44f1a83](https://github.com/mathiasgredal/overleaf/commit/44f1a83ab963a6ee8a82bcc493243b57602e1460)
> 
> To use this code you just clone the repo, switch to the arm64 branch, checkout the commit and change directory to server-ce. Then run make build-base followed by make build-community.
> 
> To run these newly built container images you can just use the provided docker-compose.yml file, but change it to use the new image. For my server I use traefik for HTTPS, and my compose file looks something like this: https://gist.github.com/mathiasgredal/6bb33613678316ffd6388a24f2db7e54

Thanks, for the tip, after 1 to 2hours of compilation it perfectly worked ! 

However I struggled to easily import large project (my thesis for example). I tried to push on the volume under some `compiling` directory, but creating a file or a directory certainly need some actions on database also I guess. Also there is no git feature (link a project with a git repository). It's just informal for those who go through the same process.

**Comment by das7pad** [comment] 2022-01-26 17:27
Closing as duplicate of https://github.com/overleaf/overleaf/issues/881. Consider adding a :+1: there.

**Closed by das7pad** 2022-01-26 17:27 UTC
