### ISSUE TITLE
502 Bad Gateway after updating Ubuntu packages

### ISSUE THREAD

**Issue by SimonUzL** [overleaf/overleaf#1199] opened 2024-03-22 08:17 UTC
## Steps to Reproduce

1. Setup WSL
2. apt update 
3. apt dist-upgrade
4. Install docker: https://docs.docker.com/engine/install/ubuntu/
5. git clone https://github.com/overleaf/toolkit.git ./overleaf-toolkit
6. bin/init
7. bin/up

## Expected Behaviour

Overleaf should be available under http://localhost:80

## Observed Behaviour

502 Bad Gateway

## Context

After upgrading the packages on my Ubuntu Server and rebooting, I get 502 Bad Gateway.

## Technical Info

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Signed in as:
* Project and/or file:

## Analysis

I am using docker `5:26.0.0-1~ubuntu.22.04~jammy`

but if I use: `5:23.0.0-1~ubuntu.22.04~jammy`, then everything works as expected. Also `5.25` works.

**Comment by ykorzikowski** [comment] 2024-03-22 11:06
I get the same error, but just running the container with native linux. Its the same image I build two weeks ago. Did not find the error, yet.

**Comment by johannesjahn** [comment] 2024-03-22 12:11
Downgrading docker to `5.25` or `5.23` didn't work for me. Any way to quickfix for now?

**Comment by KKraljic** [comment] 2024-03-22 14:31
The issue referenced here seems to be the same:
https://github.com/overleaf/overleaf/issues/1146

The solution mentioned there helped me in finding a workaround:

> docker exec -it <overleaf_container_name> /bin/bash
> # execute the following commands within the overleaf container
> sed -i 's/127.0.0.1/localhost/g' /etc/nginx/sites-enabled/sharelatex.conf
> /etc/init.d/nginx reload

**Comment by ykorzikowski** [comment] 2024-03-22 14:42
I solved this by adding this to my docker-compose.yml. And make sure you are using the docker-compose v2 API. (`docker compose up`instead of old way `docker-compose up`)

```yaml
services:
[...]
  overleaf:
    [...]
    sysctls:
        - net.ipv6.conf.all.disable_ipv6=1
```

**Comment by KKraljic** [comment] 2024-03-22 14:45
Yep, I can confirm that. The same workaround is described here: https://github.com/overleaf/overleaf/issues/1168 and works also on my system great!

**Comment by ThexXTURBOXx** [comment] 2024-03-22 18:38
This can be fixed through https://github.com/overleaf/overleaf/issues/1146#issuecomment-1709237699

**Comment by mlevans0** [comment] 2024-04-04 08:16
This should be fixed in the latest release, 5.0.1, would you mind giving it a try?

Check the release notes, as there are several breaking changes: https://github.com/overleaf/overleaf/wiki/Release-Notes-5.x.x

**Comment by ThexXTURBOXx** [comment] 2024-04-04 09:11
@mlevans0 At least on my machine 5.0.1 works fine without any changes - I upgraded yesterday already... Don't know about OP, though!

**Comment by damian-anlauf** [comment] 2024-04-05 15:26
> This should be fixed in the latest release, 5.0.1, would you mind giving it a try?
> 
> Check the release notes, as there are several breaking changes: https://github.com/overleaf/overleaf/wiki/Release-Notes-5.x.x

Can also confirm. 5.0.1 fixed the issue for me. 
FYI, I'm using a regular compose.yaml, not the Overleaf Toolkit.

**Comment by mlevans0** [comment] 2024-04-11 08:50
Changes were made inside the container, so it won't matter how your instance is deployed.

**Comment by SimonUzL** [comment] 2024-04-20 11:25
I can confirm, that the solution by @ykorzikowski works. Thank you very much for the hint. I was then able to upgrade docker to the newest version. I have not yet tested 5.0.1, but it seems to be a bad idea, according to the documentation, to do it now.

**Comment by mlevans0** [comment] 2024-04-22 09:43
Thanks for confirming. 5.0.2 has been released (https://github.com/overleaf/overleaf/wiki/Release-Notes-5.x.x) so I'll close this issue.

**Closed by mlevans0** 2024-04-22 09:43 UTC

**Comment by wakawakaaa** [comment] 2025-03-14 23:07
With new Docker image (sharelatex/sharelatex:5.3.2) there is nothing runs on 4000, and I get 502 Bad Gateway error, Is there any one have fix for it? Thanks

```
root@8f2ec5328495:/overleaf# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      202/nginx: master p
tcp        0      0 127.0.0.1:3054          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:3049          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:3048          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:3042          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:3036          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:3026          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:3016          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:3013          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:3010          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:3009          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:3003          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.11:46723        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      202/nginx: master p
tcp6       0      0 :::3100                 :::*                    LISTEN      -
tcp6       0      0 :::10843                :::*                    LISTEN      -
udp        0      0 127.0.0.11:39936        0.0.0.0:*                           -
```
