### ISSUE TITLE
BibLaTeX not working

### ISSUE THREAD

**Issue by ZelnickB** [overleaf/overleaf#1030] opened 2022-06-26 00:36 UTC
*Please see [TeX StackExchange question \#648865](https://tex.stackexchange.com/questions/648865).*

## Steps to Reproduce

1. Run `docker exec -i sharelatex tlmgr install biblatex`
2. Within a project, create a references database file according to the BibTeX format, and use `\autocite` to reference a source in the references database.
3. Compile.

## Expected Behaviour

The citation appears in the compiled document.

## Observed Behaviour

No citations appear in the compiled document, and I get error messages in the side pane.

<img width="610" alt="Screen Shot 2022-06-25 at 20 25 41" src="https://user-images.githubusercontent.com/34197604/175794530-ea46cd63-3629-4ab6-a445-9dbbd2f4589f.png">

## Technical Info

ShareLaTeX is running in a Docker container on MacOS: 12.4 via Docker Desktop: 4.9.1, Engine: 20.10.16, Compose: v2.6.0, Credential Helper: v0.6.4, Kubernetes: v1.24.0, Snyk: v1.827.0.

The project is using `subfiles`.

Overleaf gives me the option to download the following files (and *only* the following files): aux file, [bcf file](https://pastebin.com/0EjA4xDs), log file, out file, pdf file, run.xml file, stdout file, synctex.gz file, and toc file. If you would like a copy of any of them, please let me know.

## Analysis

The problem, I think, is that `\addbibresource{references.bib}` is not doing anything at all. I tried changing it to things like `\addbibresource{referencesloremipsum.bib}` and `\addbibresource{references.asdfbib}`, and I did not get any error messages saying that those files did not exist.

I have spent a while trying this with and without Biber installed (via `tlmgr install biber`), etc, and nothing works. I believe that using the BibTeX fallback may have worked (I am not sure), but I don't want to do that.

**Comment by dmackinnon1** [comment] 2022-06-28 18:22
@ZelnickB - could you try reproducing the issue with the same project on https://www.overleaf.com? If you can reproduce it there, please send the URL in a support request to support@overleaf.com. While this may be a CE issue, it would be good to take a look and see if it is a project issue. Projects structure and content can sometimes lead to issues in reading in bib resource files.

**Comment by tim-rohrer** [comment] 2022-08-21 02:03
I can chime in here and say that I seemed to be having a similar issue with BibLaTeX not working on the CE that I installed tonight. Through `tlmgr` I added `biblatex` and `biber` (not sure the latter was required?).

Also, I created an account on https://www.overleaf.com and copied my files over. The problem _did not_ occur there. Only with the CE I installed locally.

I'm not trying to use `\autocite`. 

I seem to get the same errors:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/7756865/185771999-a805cf35-8e67-4196-81ec-285de06b68e5.png">

Here is [a gist](https://gist.github.com/tim-rohrer/741ad7e9ef118953a477e82862a77c48) showing the complete log I see.

For the actual reference, I just copied this one:

```
@misc{knuthwebsite,
    author    = "Donald Knuth",
    title     = "Knuth: Computers and Typesetting",
    url       = "http://www-cs-faculty.stanford.edu/\~{}uno/abcde.html"
}
```

I'm happy to try and provide more information if it will help.

@ZelnickB, if you were able to resolve this already, please let me know what you did.

**Comment by ZelnickB** [comment] 2022-08-21 15:03
@dmackinnon1, sorry, I didn't have a chance to put my document into the overleaf.com editor, but as Tim said, it looks like the problem is not occurring there.

@tim-rohrer, my goal in using a self-hosted edition of Overleaf was to avoid a TeX installation on my laptop, so my workaround was simply to use a TeX editor inside of a VM (I ended up not using Overleaf at all). I know that's not the solution that you're looking for—sorry about that.

**Comment by tim-rohrer** [comment] 2022-08-21 21:38
No problem @ZelnickB. I appreciate you getting back to me.

I've got time, and with luck @dmackinnon1 and I can get this resolved.

**Comment by ThomasKra** [comment] 2022-08-22 15:39
Same issue here - updated to 3.2.0 today. Since then no biber run possible. Is there a fix available yet?

**Comment by aaronzi** [comment] 2022-08-22 20:51
I found a solution for the problem. Seems like you need to add a "," add the end of the last line on each entry in the .bib file too.

Example:
```
@misc{knuthwebsite,
    author    = "Donald Knuth",
    title     = "Knuth: Computers and Typesetting",
    url       = "http://www-cs-faculty.stanford.edu/\~{}uno/abcde.html",
}
```

**Comment by tim-rohrer** [comment] 2022-08-22 21:12
> I found a solution/workaround for the problem. Seems like you need to add a "," at the end of the last line on each entry in the .bib file too. Unfortunately this onky works with natbib if thats an alternative for you.

It might be, I'll have to experiment more. Seems like your solution simply switches packages whereas this issue is specific to BibLaTeX. That said, my reasoning for using an bibliography management tool other than the default was that I wanted enhanced support for online-type references, something which I read BibLaTeX has compared to BibTex.

**Comment by aaronzi** [comment] 2022-08-22 21:21
> Seems like your solution simply switches packages whereas this issue is specific to BibLaTeX

Yes, thats true. I thougt I tested it with biblatex when I tried to fix it by adding a comma but unfortunately I used the wrong package. The solution seems not to work with Biblatex :/

Hopefully you or somebody else finds a solution. I would also prefer to use Biblatex for my Paper but I will probably also get away with natbib if there isn't any solution.

**Comment by aaronzi** [comment] 2022-08-22 21:38
Btw, Biblatex as alternative to the Biber backend seems to work. Maybe this helps with findinding the issue.

**Comment by tim-rohrer** [comment] 2022-08-22 22:30
> Btw, Biblatex as alternative to the Biber backend seems to work. Maybe this helps with findinding the issue.

Please elaborate on this for me as I'm basically a newbie when it comes to Overleaf. I last used LaTeX back in the mid-1990s.

How should this line look to accomplish what you're proposing?

```latex
\usepackage[
backend=biblatex,
style=alphabetic,
]{biblatex}
```

**Comment by aaronzi** [comment] 2022-08-23 06:22
> How should this line look to accomplish what you're proposing?

This is exactly what I meant. But unfortunately biblatex as backend is way older than biber and has less features. This means it's not a very good alternative.

**Comment by tim-rohrer** [comment] 2022-08-23 13:12
Thanks. I do still have some time so hopefully @dmackinnon1 will come up with a better solution.

**Comment by tim-rohrer** [comment] 2022-09-26 21:15
As mentioned, #1042 and this issue seem similar, but v3.2.2 doesn't seem to fix this issue.

Any update?

**Comment by Polyfly** [comment] 2022-10-06 04:07
The latex package biber can be installed with `tlmgr install biber`, but the background service is not available in the Docker container. This must be added manually. It is essential to ensure that the two versions of Biber and Biblatex are compatible with each other! Otherwise a faulty installation can lead to errors.

I'll try to describe the following steps in detail and use this [documentation](https://mirror.informatik.hs-fulda.de/tex-archive/biblio/biber/base/documentation/biber.pdf).
1. connect to the Docker container: `$ docker exec -it <CONTAINERID> /bin/sh`
2. navigate to the /home directory: `$ cd /home`
3. download the latest version of biber: `$ wget https://github.com/plk/biber/archive/refs/tags/v2.18.zip`
4. unpack the file: `$ unzip v2.18.zip`
5. navigate to the new folder: `$ cd biber-2.18/`
6. open the CPAN shell: `$ cpan`
7. install the modules: `> install Module::Build` and then `> install PAR::Packer`
8. close the CPAN shell: `> quit`
9. execute the command: `$ perl ./Build.PL`
10. optional: if dependencies are missing, they can be installed with the command: `$ ./Build installdeps`
11. run the test instruction: `$ ./Build test`
12. Attention: execute the next command only if the test run was successfull: `$ ./Build install`
13. Installation completed. Compile your document again and observe if the literature is referenced correctly.

Maybe the description is helpful for you.

**Comment by tim-rohrer** [comment] 2022-10-07 19:38
I appreciate this, but no joy. I even made sure I was starting with a freshly downloaded v3.2.2 image. 

The first step I have an issue with is the dependencies, where I can't seem to get these installed:

```sh
# perl ./Build.PL
WARNING: the following files are missing in your kit:
	META.json
	META.yml
Please inform the author.

Checking prerequisites...
  requires:
    !  LWP::Protocol::https is not installed
    !  XML::LibXSLT is not installed
    !  perl (5.30.0) is installed, but we need version >= 5.32.0

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Run 'Build installdeps' to install missing prerequisites.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'biblatex-biber' version '2.18'
```

I'm assuming the perl discrepancy is an issue with the image? Can I install the other two from the `cpan` shell?

**Comment by Polyfly** [comment] 2022-10-07 19:50
The missing dependencies can be installed with the command: `$ ./Build installdeps`

**Comment by tim-rohrer** [comment] 2022-10-07 21:09
Apologies, I wasn't clear. 

I did run `./Build installdeps`, and bunches of them installed, but not those three prerequisites.

**Comment by Polyfly** [comment] 2022-10-07 21:34
You could still try the following:

Update the Perl installation with `$ apt update`.
And install the required packages manually in cpan shell.

**Comment by tim-rohrer** [comment] 2022-10-08 11:22
Installing `LWP::Protocol::https` I get:

```sh
*** Be sure to use the same compiler and options to compile your OpenSSL, perl,
    and Net::SSLeay. Mixing and matching compilers is not supported.

******************************************************************************
* COULD NOT FIND LIBSSL HEADERS                                              *
*                                                                            *
* The libssl header files are required to build Net-SSLeay, but they are     *
* missing from /usr. They would typically reside in /usr/include/openssl.    *
*                                                                            *
* If you are using the version of OpenSSL/LibreSSL packaged by your Linux    *
* distribution, you may need to install the corresponding "development"      *
* package via your package manager (e.g. libssl-dev for OpenSSL on Debian    *
* and Ubuntu, or openssl-devel for OpenSSL on Red Hat Enterprise Linux and   *
* Fedora).                                                                   *
******************************************************************************
Warning: No success on command[/usr/bin/perl Makefile.PL INSTALLDIRS=site]
  CHRISN/Net-SSLeay-1.92.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- NOT OK
  SULLR/IO-Socket-SSL-2.075.tar.gz
  Has already been unwrapped into directory /root/.cpan/build/IO-Socket-SSL-2.075-0
Warning: Prerequisite 'Net::SSLeay => 1.46' for 'SULLR/IO-Socket-SSL-2.075.tar.gz' failed when processing 'CHRISN/Net-SSLeay-1.92.tar.gz' with 'writemakefile => NO '/usr/bin/perl Makefile.PL INSTALLDIRS=site' returned status 256'. Continuing, but chances to succeed are limited.
Configuring S/SU/SULLR/IO-Socket-SSL-2.075.tar.gz with Makefile.PL
```

Install fails. Re-execution of `perl ./Build.PL`:

```sh
# perl ./Build.PL
WARNING: the following files are missing in your kit:
	META.json
	META.yml
Please inform the author.

Checking prerequisites...
  requires:
    !  LWP::Protocol::https is not installed
    !  XML::LibXSLT is not installed
    !  perl (5.30.0) is installed, but we need version >= 5.32.0

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Run 'Build installdeps' to install missing prerequisites.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'biblatex-biber' version '2.18'
```

Will the next release of the image include biber?

Thank you!

Tim

**Comment by TsingLoo** [comment] 2022-10-14 15:23
same problem here, updated today

**Comment by tim-rohrer** [comment] 2022-10-14 15:28
Good to hear I'm not alone :-)

I appreciate @polyfly's efforts with this, and I hope to hear more from the team. Ideally this will be fixed in the image.

**Comment by jettrich** [comment] 2022-10-27 08:01
Today I've upgraded my containers using overleaf-toolkit, upgraded the Linux system inside sharelatex container, and followed the steps @Polyfly suggested [above](https://github.com/overleaf/overleaf/issues/1030#issuecomment-1269282125), and now my local overleaf-ce instance is correctly compiling using biber backend! :smile:

**Comment by tim-rohrer** [comment] 2022-10-27 13:49
What updates did you do to the Linux container? What versions?

I'm using the regular Docker setup because I'm trying to run this behind SWAG.

**Comment by jettrich** [comment] 2022-10-30 12:32
Dear @tim-rohrer, I entered the sharelatex machine using `bin/shell sharelatex` and found that `mtxrun --generate` gave me `...command not found...`. Thus, I did a 
```
apt update
apt -y upgrade
```
Since `mtxrun` still wasn't available, I searched the web in order to see which package I will need to get `mtxrun` installed, which I found is `context`. Thus I did...
```
apt install context
```
Then I ran
```
tlmgr install scheme-full
tlmgr install biblatex
tlmgr install biber
mtxrun --generate
mktexlsr
updmap-sys
fmtutil-sys --all
```
And quite naively I also tried `apt install biber`, but that did not help either for overleaf-CE. Following the solution of @Polyfly, including the `./Build installdeps` steps mentioned above, `biber` is now working correctly inside my local sharelatex container. To be honest, I'm not an expert, i.e. I'm not sure if all the steps I did are all necessary and correct, but it works for me ;)   

Finally, I did a commit of the docker container as described in the overleaf-toolkit manual, in order to make the changes persistent.

**Comment by Haschtl** [comment] 2022-11-02 09:29
I had this issue with overleaf-toolkit 3.2. For me this issue was fixed after updating the overleaf-toolkit to 3.3 and then just running
`tlmgr install scheme-full`.

**Comment by Haschtl** [comment] 2022-11-02 12:22
I followed the instructions of @Polyfly, but tests all failed. 
So I executed the commands @jettrich suggested and ran the tests again with success!
I can confirm biber is working now

**Comment by Typiqally** [comment] 2022-11-16 18:47
> The latex package biber can be installed with `tlmgr install biber`, but the background service is not available in the Docker container. This must be added manually. It is essential to ensure that the two versions of Biber and Biblatex are compatible with each other! Otherwise a faulty installation can lead to errors.
> 
> I'll try to describe the following steps in detail and use this [documentation](https://mirror.informatik.hs-fulda.de/tex-archive/biblio/biber/base/documentation/biber.pdf).
> 
> 1. connect to the Docker container: `$ docker exec -it <CONTAINERID> /bin/sh`
> 2. navigate to the /home directory: `$ cd /home`
> 3. download the latest version of biber: `$ wget https://github.com/plk/biber/archive/refs/tags/v2.18.zip`
> 4. unpack the file: `$ unzip v2.18.zip`
> 5. navigate to the new folder: `$ cd biber-2.18/`
> 6. open the CPAN shell: `$ cpan`
> 7. install the modules: `> install Module::Build` and then `> install PAR::Packer`
> 8. close the CPAN shell: `> quit`
> 9. execute the command: `$ perl ./Build.PL`
> 10. optional: if dependencies are missing, they can be installed with the command: `$ ./Build installdeps`
> 11. run the test instruction: `$ ./Build test`
> 12. Attention: execute the next command only if the test run was successfull: `$ ./Build install`
> 13. Installation completed. Compile your document again and observe if the literature is referenced correctly.
> 
> Maybe the description is helpful for you.

The above solution worked for me, but it is missing one instruction. The default sharelatex image does not contain libxslt out-of-the-box, which is required during the `./Build installdeps` command. You can install it using the following command:

```sh
apt-get install libxml-libxslt-perl
```

Hope it helps some people.

**Comment by DrauzJu** [comment] 2022-11-17 16:28
@Typiqally Thanks a lot, this helped me!

When running `./Build test`, I still got the error `Can't load '/usr/local/lib/x86_64-linux-gnu/perl/5.30.0/auto/Text/BibTeX/BibTeX.so' for module Text::BibTeX: libbtparse.so: cannot open shared object file: No such file or directory at /usr/lib/x86_64-linux-gnu/perl/5.30/DynaLoader.pm line 193`. The solution is to just run `ldconfig` to rebuild the cache of shared libraries. Now it also works for me

**Comment by toastedcrumpets** [comment] 2022-11-18 09:20
Thank you guys! this is something I've been playing with for months trying to get working. To help others, here's a docker file that takes the overleaf CE, installs common tex packages, and installs a working copy of biber. Its not optimised but you can easily tweak this if you like. Be warned this image is 2.2Gb!

```
FROM sharelatex/sharelatex:3.3.2

RUN tlmgr install revtex amsmath textcase listings fncychap biblatex cancel pdfpages setspace footmisc bigfoot multirow lettrine minifp textpos subfig caption placeins epigraph pdflscape ec cm-super biber biblatex times bibtex collection-latexrecommended collection-latexextra collection-bibtexextra collection-fontsrecommended

RUN tlmgr install collection-mathscience

RUN tlmgr install collection-pstricks

RUN tlmgr install collection-fontutils

RUN tlmgr install collection-fontsextra

RUN tlmgr install collection-binextra

RUN tlmgr install xetex

RUN apt-get update && apt install -y context libxml-libxslt-perl cpanminus && rm -rf /var/lib/apt/lists/*
RUN mtxrun --generate && mktexlsr && updmap-sys && fmtutil-sys --all

RUN cpanm install Module::Build && cpanm install PAR::Packer; rm -fr root/.cpanm; exit 0

RUN cd /home && wget https://github.com/plk/biber/archive/refs/tags/v2.18.zip && unzip v2.18.zip && cd biber-2.18/ && perl ./Build.PL && ./Build installdeps && ldconfig && ./Build test && ./Build install
```

**Comment by Davey-Gravy** [comment] 2022-12-17 04:00
@toastedcrumpets, I've tested your Dockerfile and I can't seem to connect to mongo:

```
# docker run 9641860dc372
*** Running /etc/my_init.d/00_make_sharelatex_data_dirs.sh...
*** Running /etc/my_init.d/00_regen_sharelatex_secrets.sh...
generating random secrets
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/00_set_docker_host_ipaddress.sh...
*** Running /etc/my_init.d/01_nginx_config_template.sh...
Nginx: generating config file from template
Nginx: reloading config
 * Reloading nginx configuration nginx
   ...done.
*** Running /etc/my_init.d/10_delete_old_logs.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Dec 17 03:49:59 acb637195c77 syslog-ng[70]: syslog-ng starting up; version='3.25.1'
*** Running /etc/my_init.d/98_check_db_access.sh...
Checking can connect to mongo and redis
Using default settings from /overleaf/services/web/config/settings.defaults.js
Using settings from /etc/sharelatex/settings.js
Set UV_THREADPOOL_SIZE=16
Cannot connect to mongodb.
MongoServerSelectionError: connect ECONNREFUSED 172.17.0.1:27017
    at Timeout._onTimeout (/overleaf/services/web/node_modules/mongodb/lib/core/sdam/topology.js:437:30)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { 'dockerhost:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
*** /etc/my_init.d/98_check_db_access.sh failed with status 1

*** Killing all processes...
Dec 17 03:51:01 acb637195c77 syslog-ng[70]: syslog-ng shutting down; version='3.25.1'
```

**Comment by toastedcrumpets** [comment] 2022-12-17 08:11
My image is built on top of the same one used in this docker compose file
https://github.com/overleaf/overleaf/blob/main/docker-compose.yml
If you look there, you can see separate containers are needed for mongodb and redis, as well as environment variables to configure them. Happy to help more if you need it

**Comment by tillhanke** [comment] 2023-06-01 12:21
> RUN cd /home && wget https://github.com/plk/biber/archive/refs/tags/v2.18.zip && unzip v2.18.zip && cd biber-2.18/ && perl ./Build.PL && ./Build installdeps && ldconfig && ./Build test && ./Build install
> ```

Sadly this approach doesn't work with the current version of the sharelatex docker. Since the biblatex version is 3.19, which is not compatible with biber 2.18 and biber 2.19 is not able to build due to a too old version of perl. 
If anybody finds a way of implementing biber into sharelatex > 4.0 it would be really cool. 

I tried using tlmgr to install biber but overleaf does not seem to be able to use that, even though its installed and I can use it manually via the shell.

**Comment by nik-ko** [comment] 2023-08-02 14:29
> @tillhanke, I eventually found a simpler way thanks to the following issue #873, in particular this comment [#873 (comment)](https://github.com/overleaf/overleaf/issues/873#issuecomment-1498442727) My current Dockerfile looks like below and works fine with the current sharelatex
> 
> ```
> FROM sharelatex/sharelatex:4.0.1
> 
> #From this issue to force a full scheme update and install https://github.com/overleaf/overleaf/issues/873, in particular this comment https://github.com/overleaf/overleaf/issues/873#issuecomment-1498442727
> RUN export TEXLIVE_PATH=/usr/local/texlive && \
>     ls -la "${TEXLIVE_PATH}" && \
>     export TEXLIVE_VERSION="$(find ${TEXLIVE_PATH} -type d -name "2*" -printf "%f\n" | tail -1)" && \
>     export PATH="${PATH}:${TEXLIVE_PATH}/${TEXLIVE_VERSION}/bin/x86_64-linux" && \
>     echo ${PATH} && \
>     tlmgr path add && \
>     (tlmgr update --self --all || (tlmgr option repository "https://pi.kwarc.info/historic/systems/texlive/${TEXLIVE_VERSION}/tlnet-final" && tlmgr update --self --all)) && \
>     tlmgr path add && \
>     tlmgr install scheme-full && \
>     tlmgr path add```
> ```

Thank you. I modified your Dockerfile for the latest sharelatex version and also added `tlmgr install scheme-full`. I uploaded the image to Dockerhub. Now you just need to set `SHARELATEX_IMAGE_NAME=hnko/sharelatex` in `overleaf-toolkit/config/overleaf.rc` after running `bin/init` as described [here](https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md#starting-up)

**Comment by tillhanke** [comment] 2023-08-02 15:22
@toastedcrumpets Thanks! I will give this a try, I tried something simmilar, but wasn't able to get tlmgr to recognize the correct texliveversion...
Now I just have to find a way to include autocomplete for the tags into the CE version and everything would be perfect :D

**Comment by jettrich** [comment] 2023-09-18 12:29
Hi Everyone, today I've tried to apply the above solutions on the latest version available via overleaf-toolkit. Unfortunately, I found that the latest release (4.1.1) is using biblatex-3.19 which requires biber-3.19, thus I changed the commands accordingly... BUT: biber-3.19 requires Perl-5.32, whereas the underlying focal-fossa provides Perl-5.30. I don't think, that it makes sense to install a complete new Perl environment inside focal-fossa, thus I would like to ask, if someone has an idea about how to solve this? Maybe it's better to move the whole image to jammy-jellyfish?

Please, let us discuss and find a solution asap, in the meantime I will try to proceed with an older version (4.05 or something)!

**Comment by toastedcrumpets** [comment] 2023-09-18 13:37
My system builds fine on 4.1.1 and runs biblatex with the biber backend, here's my Dockerfile

`FROM sharelatex/sharelatex:4.1.1

RUN sed -i 's/127.0.0.1/localhost/g' /etc/nginx/sites-enabled/sharelatex.conf

#From this issue to force a full scheme update and install https://github.com/overleaf/overleaf/issues/873, in particular this comment https://github.com/overleaf/overleaf/issues/873#issuecomment-1498442727
RUN export TEXLIVE_PATH=/usr/local/texlive && \
    ls -la "${TEXLIVE_PATH}" && \
    export TEXLIVE_VERSION="$(find ${TEXLIVE_PATH} -type d -name "2*" -printf "%f\n" | tail -1)" && \
    export PATH="${PATH}:${TEXLIVE_PATH}/${TEXLIVE_VERSION}/bin/x86_64-linux" && \
    echo ${PATH} && \
    tlmgr path add && \
    (tlmgr update --self --all || (tlmgr option repository "https://pi.kwarc.info/historic/systems/texlive/${TEXLIVE_VERSION}/tlnet-final" && tlmgr update --self --all)) && \
    tlmgr path add && \
    tlmgr install scheme-full && \
    tlmgr path add`

Note the sed line is needed to fix issue #1146

**Comment by jettrich** [comment] 2023-09-18 15:24
Thanks a lot to @toastedcrumpets, using your Dockerfile I was able to build an image and use it successfully, great! I'm not sure what I did wrong before - however, I can confirm, that the Dockerfile works!

**Comment by Doomsdayrs** [comment] 2023-10-13 03:24
Alright, we have community feedback and solutions.

What is upstream doing and why haven't they stepped in?

**Comment by toastedcrumpets** [comment] 2023-10-13 06:37
They explicitly say they don't include a full Tex distribution due to image
size, and I believe it. My current image is 3Gb and takes ages to deploy...

**Comment by Bomme** [comment] 2023-12-12 14:53
The only important command that fixes it for me was:
```
tlmgr path add
```
after doing the `scheme-full` install.

**Comment by jpaodev** [comment] 2024-02-14 12:17
> libbtparse

For everyone wondering what else could be needed, all my tests failed as well, even after installing `libxml-libxslt-perl`.

After finding this advice on [a StackOverflow post](https://stackoverflow.com/questions/14678496/perl-dynaloader-pm-libbtparse-so-shared-object-missing):
> I got this error after installing the Text::BibTeX module with cpanm on Ubuntu 14.04. The problem was solved by installing the libbtparse-dev package .. 
by [Håkon Hægland](https://stackoverflow.com/users/2173773/h%c3%a5kon-h%c3%a6gland)

and installing the said dependency using apt, all tests did indeed pass. Did not install yet, however.

**Comment by cgpsJie** [comment] 2024-04-01 07:22
I met the same problem. It seems that `biber` is not added to $PATH.

I manually created a link of `biber` to `/usr/local/bin` and it works.
Try

```bash
ln /usr/local/texlive/2023/bin/x86_64-linux/biber  /usr/local/bin/biber
```
in the docker shell, 
where 2023 should be replaced with your texlive version.

**Comment by leonyannnick** [comment] 2024-04-15 19:05
> I met the same problem. It seems that `biber` is not added to $PATH.
> 
> I manually created a link of `biber` to `/usr/local/bin` and it works. Try
> 
> ```shell
> ln /usr/local/texlive/2023/bin/x86_64-linux/biber  /usr/local/bin/biber
> ```
> 
> in the docker shell, where 2023 should be replaced with your texlive version.

This solved the problem for me, thank you!

**Comment by das7pad** [comment] 2024-08-29 12:18
Hello,

I'm afraid we cannot offer LaTeX help for specific templates or packages in Overleaf Community Edition. Our Server Pro offering provides you with access to the same optimized LaTeX environment as used for overleaf.com. We run [extensive tests with the overleaf.com gallery templates](https://www.overleaf.com/learn/latex/Overleaf_and_TeX_Live#About_Overleaf%E2%80%99s_upgrade_process) when preparing new TeXLive releases and generally make sure that templates either compile with the new version or leave them at their previous TeXLive release. Server Pro customers get access to our historic TeXLive releases as well to ensure older projects continue to work.
You can find more information on Server Pro here: https://www.overleaf.com/for/enterprises

Greetings,
Jakob

**Closed by das7pad** 2024-08-29 12:18 UTC
Labels: latex discussion

**Comment by DamianoP** [comment] 2024-10-27 15:24
> > I met the same problem. It seems that `biber` is not added to $PATH.
> > I manually created a link of `biber` to `/usr/local/bin` and it works. Try
> > ```shell
> > ln /usr/local/texlive/2023/bin/x86_64-linux/biber  /usr/local/bin/biber
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in the docker shell, where 2023 should be replaced with your texlive version.
> 
> This solved the problem for me, thank you!
> 
> EDIT: If you are running this issue on newer versions, just replace the 2023 by 2024.
> 
> > ```shell
> > ln /usr/local/texlive/2024/bin/x86_64-linux/biber  /usr/local/bin/biber
> > ```

This fix works perfectly with the current version.
Since it is necessary to use the bibliography in the papers correctly, would it be possible to add it directly in the official installation or in the official documentation?
New users will certainly have difficulty finding this fix, and I think it would help a lot of people if it were already integrated into the official image by default....

**Comment by dannthi** [comment] 2025-06-15 15:52
> > I met the same problem. It seems that `biber` is not added to $PATH.
> > I manually created a link of `biber` to `/usr/local/bin` and it works. Try
> > ln /usr/local/texlive/2023/bin/x86_64-linux/biber  /usr/local/bin/biber
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in the docker shell, where 2023 should be replaced with your texlive version.
> 
> This solved the problem for me, thank you!
> 
> EDIT: If you are running this issue on newer versions, just replace the 2023 by 2024.
> 
> > ln /usr/local/texlive/2024/bin/x86_64-linux/biber  /usr/local/bin/biber

On new installs use

`ln /usr/local/texlive/2025/bin/x86_64-linux/biber  /usr/local/bin/biber`
