### ISSUE TITLE
safari 15.6.1 select the text of one line (chinese) cannot highlight at the same time

### ISSUE THREAD

**Issue by CymaticsCC** [overleaf/overleaf#1105] opened 2023-03-23 14:19 UTC
I am using a sharelatex 3.5.0 deployed by docker.

The browser i using safari 15.6.1.

When i try to select some content of one line or multiple line using mouse cursor,  the selected content cannot be highlighted as selected at the same time. After waiting some seconds when stop mouse, it be highlighted. 

The problem only appear in the **chinese environment**, when i edit english file, it works normaly. 

Also, i try the another browser like chrome, it works normally. Also, i tried another version sharelatex (2.5.0) using safari, it works normaly also. 

It seams the **sharelatex (3.5.0)** has some problems for selecting **chinese content** using the **safari (15.6.1)**

**Comment by aeaton-overleaf** [comment] 2023-04-12 12:49
Hi! Thanks for reporting this issue. Would it be possible to provide a screenshot or screen recording showing the editor and how to reproduce it?

Do you know whether the same issue occurs when editing a project on [overleaf.com](https://www.overleaf.com)?

**Comment by aeaton-overleaf** [comment] 2023-04-12 13:24
Thanks, glad you're finding it easy to use Overleaf. 

I'll close this issue, but feel free to re-open it with more information if the problem is encountered again in the future.

**Closed by aeaton-overleaf** 2023-04-12 13:24 UTC
