### ISSUE TITLE
Request: Overleaf on arm64

### ISSUE THREAD

**Issue by 40417256** [overleaf/overleaf#881] opened 2021-04-30 07:24 UTC
Hello,

I read the past tickets and understand the CE edition is not supported on arm64. This is a pity, as they are several use cases for this.

- The pi4 has enough cpu power and memory to run it.
- It can be used for small deployments at very little cost.
- It can be used when it is not possible to (expose) store information on the internet (confidentiality).
- Nest gen of pi will certainly have AES (allowing to do full encryption), see my point above.

I would really enjoy having the possibility to run it on my pi as a container.

Thank you,

Eric

**Comment by leemgs** [comment] 2021-05-29 03:34
> The pi4 has enough cpu power and memory to run it.

However, I think that the major bottleneck will be  low-end computing power of RPI4 and external microSD.

**Comment by 40417256** [comment] 2021-05-30 11:49
> However, I think that the major bottleneck will be low-end computing power of RPI4 and external microSD.

The Pi4 has USB3 storage, and enough CPU to run Ubuntu desktop. We are not asking for a full server running hundreds of compilations at the time. I still think it is worth the try.

**Comment by mathiasgredal** [comment] 2022-01-26 23:42
I have been looking into a fix for this, and it seems that the package [fast-crc32c](https://github.com/ashi009/node-fast-crc32c) is the blocker for getting this to work. Since there has been an open [pull request](https://github.com/ashi009/node-fast-crc32c/pull/28) for this in almost a year, I assume that the package author is no longer maintaining this package. One workaround for this would be to use [patch-package](https://github.com/ds300/patch-package), and apply the patch ourselves. I would like to know whether you would accept a pull request using this method, since having arm64 support in the official overleaf codebase would be nice.

**Comment by 40417256** [comment] 2022-01-27 13:55
Thank you for looking into the problem Mathias, it would be very nice indeed to have arm64 support.

**Comment by hughplay** [comment] 2022-02-21 01:46
@mathiasgredal I have tried to install overleaf as you tell in https://github.com/overleaf/overleaf/issues/957#issuecomment-924423002. I got the docker image to work successfully on my raspberry pi 4b. Very nice! However, I find the version of textlive is not up-to-date so tlmgr updates failed. (texlive 2017 < 2021)

Is this expected or not?

**Comment by mathiasgredal** [comment] 2022-02-21 10:52
I suspect it has something to do with the apt repositories not staying up to date. I tried to redo the texlive install, such that it matches the way overleaf does it in this PR #991 along with keeping fast-crc32. It has however become so out of date that i have closed it. I plan to redo it and open a new PR, unless someone gets to it before me.

**Comment by aeaton-overleaf** [comment] 2022-08-11 10:06
It should now be possible to run Overleaf on the `arm64` architecture. As the [`sharelatex/sharelatex`](https://hub.docker.com/r/sharelatex/sharelatex) Docker image is only published as `amd64`, you'll need to build it locally following [the instructions in this repository](https://github.com/overleaf/overleaf#overleaf-docker-image). Then, in [Overleaf toolkit](https://github.com/overleaf/toolkit/), run `docker tag sharelatex/sharelatex sharelatex/sharelatex:3.1.0` (where `3.1.0` matches the version in the toolkit's `config/version` file), then run `bin/up` to start the services.

**Closed** 2022-08-11 10:06 UTC

**Comment by elendil7** [comment] 2024-05-10 12:38
Hello @aeaton-overleaf 

Would it be possible for you to automate building this arm image and pushing it to docker hub? I am struggling to do so using your instructions, and it would be nicer to just pull the image with the arm tag directly from my docker-compose file.

Thanks in advance.

Example:
Instead of:
```
overleaf:
    image: sharelatex/sharelatex:latest
```
I could have something like:
```
overleaf:
    image: sharelatex/sharelatex:latest-arm
```

Link to docker hub: https://hub.docker.com/r/sharelatex/sharelatex

**Comment by npasslick** [comment] 2024-05-13 23:30
It would be nice if an ARM64 image could be provided in the Docker Hub. I'm using Ampere ARM server and while I do manage to compile an ARM Docker image, I cannot tell which commit corresponds to the latest Overleaf CE version because the code here on GitHub is rather sparsely documented / not tagged with a version.

**Comment by albertopasqualetto** [comment] 2024-06-12 15:28
Any progresses? Dockerfiles building guides seem to be incomplete.

**Comment by aikooo7** [comment] 2024-08-15 12:37
Why is this closed @aeaton-overleaf ? This is not fixed, my example is that my machine doesn't support buildx so I can't build the image, I tried removing it but I couldn't. This could be all be fixed, if you know, the inage had arm64 support...

**Comment by aikooo7** [comment] 2024-08-15 13:21
I was able to build with the commit e36de5a since it is the last commit without buildx

**Comment by ibpop** [comment] 2025-02-27 12:20
I managed to build the image on arm64 the way @aeaton-overleaf wrote:
1. make build-base and make build-community from server-ce/ in overleaf repository. It creates sharelatex docker images in the system.
2. docker tag sharelatex/sharelatex:main sharelatex/sharelatex:3.1.0 (where 3.1.0 matches the version in the toolkit's config/version file)
3. run bin/up from overleaf-toolkit directory
And it spins up on my remote machine. (I cannot connect to it for now, but I think it's the IP problem. The image seems to work.)

**Comment by weathon** [comment] 2025-03-31 02:25
> I managed to build the image on arm64 the way [@aeaton-overleaf](https://github.com/aeaton-overleaf) wrote:
> 
> 1. make build-base and make build-community from server-ce/ in overleaf repository. It creates sharelatex docker images in the system.
> 2. docker tag sharelatex/sharelatex:main sharelatex/sharelatex:3.1.0 (where 3.1.0 matches the version in the toolkit's config/version file)
> 3. run bin/up from overleaf-toolkit directory
>    And it spins up on my remote machine. (I cannot connect to it for now, but I think it's the IP problem. The image seems to work.)

This worked for me. For the first time, docker says it cannot find sharelatex:main, but somehow it found it later and can tag it and I am able to run it

**Comment by Yeshey** [comment] 2025-04-17 01:06
> I managed to build the image on arm64 the way [@aeaton-overleaf](https://github.com/aeaton-overleaf) wrote:
> 
>     1. make build-base and make build-community from server-ce/ in overleaf repository. It creates sharelatex docker images in the system.
> 
>     2. docker tag sharelatex/sharelatex:main sharelatex/sharelatex:3.1.0 (where 3.1.0 matches the version in the toolkit's config/version file)
> 
>     3. run bin/up from overleaf-toolkit directory
>        And it spins up on my remote machine. (I cannot connect to it for now, but I think it's the IP problem. The image seems to work.)

Took me a long while but that's the method that ended up working for me as well. Seems like it's just a matter of marking the official overleaf docker as aarm64 capable?

**Comment by luftaquila** [comment] 2025-04-22 09:19
Same working confirmed here. Why not adding an official tag for arm64?

**Comment by axnj2** [comment] 2025-05-14 09:11
Would it be possible to enable docker-compose on arm64 ?

**Comment by mlevans0** [comment] 2025-05-20 09:40
Unfortunately, due to limitations with our current build pipeline, we are unable to provide `arm64` images at the moment. We're sorry for the limitation here.

**Comment by luftaquila** [comment] 2025-05-20 10:30
As just for a tip you might already know, Oracle Cloud has an always-free eligible Ampere A1 instance that runs on arm64. Self-hosted GitHub runner on there will make it able to build arm64 image of the Overleaf. I think people asking for an arm64 image here (including me) are using that Ampere OCI instance too.

Anyway, whether or not arm64 image will be official in the future, thanks a lot for the great work!

**Comment by Yeshey** [comment] 2025-05-20 11:21
> As just for a tip you might already know, Oracle Cloud has an always-free eligible Ampere A1 instance that runs on arm64. Self-hosted GitHub runner on there will make it able to build arm64 image of the Overleaf. I think people asking for an arm64 image here (including me) are using that Ampere OCI instance too.

Same situation here

> Unfortunately, due to limitations with our current build pipeline, we are unable to provide `arm64` images at the moment. We're sorry for the limitation here.

I'll leave a link to my solution to build it in nixOS with arm support here in case anyone is in the same situation: [overleaf.nix](https://github.com/Yeshey/nixOS-Config/blob/7ab39e318fa8839e904d60f983a091328d4bf79a/modules/nixos/toHost/overleaf.nix) (it is using my older fork of overleaf tho, with full latex installed, instead of the official overleaf repo rn)
