### ISSUE TITLE
[Wiki] Creating an admin user as explained in the wiki uses a wrong syntax

### ISSUE THREAD

**Issue by DavidNiehues** [overleaf/overleaf#470] opened 2016-09-16 16:35 UTC
Hi,

I just installed sharelatex for the  first time. Apart from some minor problems it worked quite good, even without using docker. But what took me the most time was creating the first user.

The [wiki](https://github.com/sharelatex/sharelatex/wiki/Quick-Start-Guide) states, that the command is `grunt create-admin-user --email joe@example.com`, where  a `=` is missing after `--email`. Without the `=` grunt states that the task `create-admin-user` doesn't exist.

**Comment by bonanza123** [comment] 2016-10-02 10:02
For me it works as written in the wiki.

**Comment by juanjux** [comment] 2017-04-20 07:44
For me it as as in the issue (with the =).

**Comment by hrjakobsen** [comment] 2022-07-21 09:38
Duplicate of #462. I'll close the issue as the wiki was updated to reflect the correct syntax.

**Closed by hrjakobsen** 2022-07-21 09:38 UTC
