### ISSUE TITLE
A non-closed \institute command bring the whole share latex down

### ISSUE THREAD

**Issue by MSherif** [overleaf/overleaf#402] opened 2016-03-11 15:50 UTC
A non-closed \institute command bring the whole share latex down, this happens only in the open source version, not with the one on-line,  there is a MWE:

\documentclass{llncs}
\begin{document}
\title{Test}
\author{test}
\institute{ non-closed institute command
\maketitle
\end{document}

and there is the log

{"name":"clsi","hostname":"5e82b527b57c","pid":32,"level":40,"msg":"timeouts and sandboxing are not enabled with CommandRunner","time":"2016-03-11T15:41:39.835Z","v":0}
Latexmk: This is Latexmk, John Collins, 5 February 2015, version: 4.43a.
Latexmk: Changing directory to '/var/lib/sharelatex/data/compiles/56e2cc2b21eebe2200f9c50c/'
Rule 'pdflatex': File changes, etc:
   Non-existent destination files:
## Run number 1 of rule 'pdflatex'

---
## Running 'pdflatex -synctex=1 -interaction=batchmode  -recorder -output-directory="/var/lib/sharelatex/data/compiles/56e2cc2b21eebe2200f9c50c" --jobname="output"  "main.tex"'

Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
SyncTeX written on /var/lib/sharelatex/data/compiles/56e2cc2b21eebe2200f9c50c/output.synctex.gz.'output.fls' and '/var/lib/sharelatex/data/compiles/56e2cc2b21eebe2200f9c50c/outpu
t.fls' are identical (not copied) at /usr/local/bin/latexmk line 6814.
Latexmk: Log file says output to 'output.pdf'
Latexmk: ===For rule 'pdflatex', actual output 'output.pdf'
       ======appears not to match expected output '/var/lib/sharelatex/data/compiles/56e2cc2b21eebe2200f9c50c/output.pdf'
Latexmk: Undoing directory change
Latexmk: All targets (/var/lib/sharelatex/data/compiles/56e2cc2b21eebe2200f9c50c/output.pdf) are up-to-date
{"name":"clsi","hostname":"5e82b527b57c","pid":32,"level":30,"project_id":"56e2cc2b21eebe2200f9c50c","time_taken":449,"msg":"done compile","time":"2016-03-11T15:41:40.282Z","v":0}
{"name":"clsi","hostname":"5e82b527b57c","pid":32,"level":30,"directory":"/var/lib/sharelatex/data/compiles/56e2cc2b21eebe2200f9c50c","msg":"getting output files","time":"2016-03-11T15:41:40.283Z","v":0}
{"name":"clsi","hostname":"5e82b527b57c","pid":32,"level":30,"args":["/var/lib/sharelatex/data/compiles/56e2cc2b21eebe2200f9c50c","-name",".cache","-prune","-o","-type","f","-print"],"msg":"running find command","time":"2016-03-11T15:41:40.283Z","v":0}
{"name":"clsi","hostname":"5e82b527b57c","pid":32,"level":30,"cache":"/var/lib/sharelatex/data/compiles/56e2cc2b21eebe2200f9c50c/.cache/clsi","dir":"1536653dc5d","msg":"removed expired cache dir","time":"2016-03-11T15:41:40.341Z","v":0}
{"name":"clsi","hostname":"5e82b527b57c","pid":32,"level":30,"args":["--linearize","/var/lib/sharelatex/data/compiles/56e2cc2b21eebe2200f9c50c/output.pdf","/var/lib/sharelatex/data/compiles/56e2cc2b21eebe2200f9c50c/.cache/clsi/15366572470/output.pdf.opt"],"msg":"running qpdf command","time":"2016-03-11T15:41:40.349Z","v":0}
{"name":"clsi","hostname":"5e82b527b57c","pid":32,"level":40,"err":{"message":"spawn ENOENT","name":"Error","stack":"Error: spawn ENOENT\n    at errnoException (child_process.js:1011:11)\n    at Process.ChildProcess._handle.onexit (child_process.js:802:34)","code":"ENOENT","errno":"ENOENT","syscall":"spawn"},"args":["--linearize","/var/lib/sharelatex/data/compiles/56e2cc2b21eebe2200f9c50c/output.pdf","/var/lib/sharelatex/data/compiles/56e2cc2b21eebe2200f9c50c/.cache/clsi/15366572470/output.pdf.opt"],"msg":"qpdf failed","time":"2016-03-11T15:41:40.360Z","v":0}
{"name":"clsi","hostname":"5e82b527b57c","pid":32,"level":30,"req":{"url":"/project/56e2cc2b21eebe2200f9c50c/compile","method":"POST","remote-addr":"127.0.0.1","content-length":"374817"},"res":{"statusCode":200},"response-time":15717,"msg":"http request","time":"2016-03-11T15:41:40.363Z","v":0}
{"name":"clsi","hostname":"5e82b527b57c","pid":32,"level":40,"code":-1,"args":["--linearize","/var/lib/sharelatex/data/compiles/56e2cc2b21eebe2200f9c50c/output.pdf","/var/lib/sharelatex/data/compiles/56e2cc2b21eebe2200f9c50c/.cache/clsi/15366572470/output.pdf.opt"],"msg":"qpdf returned error","time":"2016-03-11T15:41:40.363Z","v":0}
{"name":"clsi","hostname":"5e82b527b57c","pid":32,"level":30,"req":{"url":"/project/56e2cc2b21eebe2200f9c50c/output/output.log","method":"GET","remote-addr":"127.0.0.1"},"res":{"statusCode":200},"response-time":4,"msg":"http request","time":"2016-03-11T15:41:40.407Z","v":0}
{"name":"clsi","hostname":"5e82b527b57c","pid":32,"level":30,"req":{"url":"/project/56e2cc2b21eebe2200f9c50c/output/output.pdf?build=15366572470","method":"GET","remote-addr":"127.0.0.1"},"res":{"statusCode":200},"response-time":2,"msg":"http request","time":"2016-03-11T15:41:40.705Z","v":0}
{"name":"clsi","hostname":"5e82b527b57c","pid":32,"level":30,"rss":"82.65","heapTotal":"70.25","heapUsed":"26.70","msg":"process.memoryUsage()","time":"2016-03-11T15:41:58.019Z","v":0}

**Comment by hrjakobsen** [comment] 2022-07-21 09:47
I was unable to reproduce this in the latest Overleaf Community Edition based on your MWE. I'll close the issue, but if it still happening please do reopen it.

**Closed by hrjakobsen** 2022-07-21 09:47 UTC
