### ISSUE TITLE
Sudden complete data loss (users and projects) overnight - but server still running

### ISSUE THREAD

**Issue by dominiktraxl** [overleaf/overleaf#951] opened 2021-08-28 14:49 UTC
## Steps to Reproduce

Unfortunately, no idea.

## Expected Behaviour

I would expect data to be stored consistently.

## Observed Behaviour

This morning, I tried to login into my overleaf server, but I couldn't since all users and projects are gone. Yesterday I could still login and all projects were still there. I didn't do anything since yesterday evening, when everything was still working as expected. The overleaf instance is still running, I can connect to it, but it appears like a new installation where I have to first create an admin user.

Using the command:
sudo docker exec mongo sh -c 'exec mongoexport -d sharelatex -c users -f email --type=csv'
now shows me zero users.  

I've set up a new admin, to check if the projects are still there, but they aren't.

## Context

My question is, is there any way to restore the projects? I have backups of
mongo_data/
redis_data/
sharelatex_data/
but no idea how i would proceed to get the projects back.

Obviously, it might also be helpful to get to the source of the problem, to prevent others running into the same nightmare.

## Technical Info

I'm running sharelatex with docker-compose on an Ubuntu 18.04.

Please let me know of any log files / config files you could possibly need to help me. Any pointer or hint is highly appreciated! A lot of work of many people has been lost, and I have no idea how and why that could have happened.

**Comment by jdleesmiller** [comment] 2021-08-28 18:49
I'm sorry to hear this happened. It sounds like something deleted all the data from the mongo database, which is not something I have seen before.

It is good that you have the data directories backed up. To restore them, it should suffice to cleanly shut down the instance, make a backup of the data directories there now, and copy the backup data directories into place, and start up the instance again. There are more details in the [documentation about backups](https://github.com/overleaf/overleaf/wiki/Backup-of-Data).

As to what happened, there may be some clues in the mongo container logs, which you should be able to read with `docker-compose logs mongo`.

Could you also confirm which version of the `sharelatex` container you are running? (You can tell from the Docker image ID, which should be one of the ones listed in the [release notes](https://github.com/overleaf/overleaf/wiki/Release-Notes-2.0).)

**Comment by dominiktraxl** [comment] 2021-08-28 19:32
Thanks for the quick reply and the information on how to restore the backup!

I've created a file with the mongo logs, you can find it here: https://github.com/dominiktraxl/share/blob/main/logs_mongo.txt
I couldn't find any clue in there as to why my database was deleted, but I'm not very well-versed with regards to mongo. Can you spot something?

The sharelatex version I'm running has the image ID 843316001077.

**Comment by jdleesmiller** [comment] 2021-09-02 10:00
Thanks for getting back to us. Did the restore work?

We've had a look at the logs. They show when the problem likely occurred but not necessarily why: 
- it looks like mongo was down from 2021-08-27T20:02:54Z to 2021-08-27T20:03:52Z
- when it came up we see indexes being built, which suggests that the CE container also restarted
- the index builds are very fast, which suggests that the collections were empty at that point

A few follow up questions:
1. The image ID you linked doesn't appear to match a release, but that may just be because you have updated tex live in the container. Could you run `docker image history sharelatex` and see if one of the layers near the top matches the release notes for a particular version? 
2. Could you run `uptime` as an indicator of whether the whole machine rebooted at 2021-08-27T20:02:54Z?
3. Where is the mongo data volume mounted on the host? If you can remove any secrets from your `docker-compose.yml` file and paste it here, that would likely tell us the answer to this.

**Comment by dominiktraxl** [comment] 2021-09-02 10:57
Thanks for the reply. And yes, the restore worked. 

Regarding your follow up questions:
1. I did update texlive, but the image ID I posted is the one before the update. I'm not running one of the Server Pro releases, but the community edition. I guess the latest image at the time was pulled, with the image ID I posted (p.s.: that image ID does show up in past issues: https://www.gitmemory.com/issue/overleaf/overleaf/756/779232355).
2. I have rebooted the machine in the meantime, but `journalctl --list-boots` tells me that the machine did not reboot at 2021-08-27T20:02:54Z (uptime time window before the first reboot after the disaster: Mon 2021-05-03 12:05:09 CEST—Sat 2021-08-28 11:23:55 CEST)
3. I'm running docker via a snap package, the mongo data volume is mounted here: `/root/snap/docker/471/mongo_data/`. Please find the `docker-compose.yml` here: https://github.com/dominiktraxl/share/blob/main/docker-compose.yml

**Comment by jdleesmiller** [comment] 2021-09-03 09:08
Thanks for checking those.

> the image ID

D'oh. I've now added the Docker Image IDs for the corresponding CE releases to the release notes. It looks like you are on [2.3.0](https://github.com/overleaf/overleaf/wiki/Release-Notes-2.0#server-pro-230).

> docker via a snap package

Interesting... I am afraid I am not very familiar with snaps. I wonder if the snap updated, which caused a docker restart and also discarded the data in that directory (or whatever directory it was using before, if it changed)? From the [snapcraft page](https://snapcraft.io/docker), it looks like there was a new stable release of the docker snap on 27 Aug, which might line up with the timeline?

**Comment by dominiktraxl** [comment] 2021-09-03 09:51
Thanks for the research, I feel like we're getting to the source of the problem. My docker snap package was indeed updated to the latest stable version. As far as I know, there's unfortunately no way to find out when the package was updated exactly (see https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1771714). But given the release data, it seems likely to me that the update and the destruction of my mongo database are indeed related. 

I'm also not very familiar with snap, using it just seemed like the easiest way to get sharelatex running at the time. I've seen multiple (numbered) subfolders in the `/root/snap/docker/` directory, and I did check all of them to see if there's one with a working mongo database from the day before the crash. But that is not the case, so I had to restore from my regular backup.

I guess we can close the issue here, it doesn't seem to be related to sharelatex, but rather snap/docker, correct me if I'm wrong. Next time I'll set up sharelatex, I'll certainly not use those snaps anymore ;) Anyway, thank you very much again for the help!

**Comment by jdleesmiller** [comment] 2021-09-03 12:13
OK, glad that we were able to find a likely root cause.

Moving away from the snap and just using the standard package seems like a reasonable thing to do. You might be able to find somewhere outside of the snap directory to bind mount the data, but there may be other restrictions at play there.

I will close this and rename it to mention snaps.

**Closed by jdleesmiller** 2021-09-03 12:13 UTC
